# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g allow-passthrough on
set -g visual-activity off
set -g default-terminal xterm-kitty
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
set -g set-clipboard on
set -g mode-keys vi
#use true colors
set -ga terminal-overrides ",xterm-kitty:Tc"
# run git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm if you dont have it
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
